webserv-blah/webserv

.gitmessage.txt
커밋메시지 컨벤션을 한글로 맞춤에 따라, 템플릿내용을 한글로  변경하였습니다.
=> build: 커밋 메시지 템플릿 변경

src/ServerManager/ServerManager.cpp, src/ServerManager/ServerManager.hpp, src/ServerManager/ServerManagerRun.cpp
srcs/ServerManager 및 하위 파일 생성
- ServerManager.hpp
- ServerManager.cpp
- ServerManagerRun.cpp //void ServerManager::run() {}
=> build: ServerManager 디렉토리 및 파일 생성

src/demultiplexer/DemultiplexerBase.hpp, src/demultiplexer/DemultiplexerBase.tpp, src/demultiplexer/KqueueDemultiplexer.cpp, src/demultiplexer/KqueueDemultiplexer.hpp, src/demultiplexer/Makefile
CRTP 패턴 기반 DemultiplexerBase, KqueueDemultiplexer 객체 구현.
향후 개선 사항
- 타 객체와 병합시 eventType 매크로를 enum으로 변경할 예정
- 타 OS에서 사용 가능하도록 확장(epoll 등)
- 객체 초기화시 serverFd 목록 넘길 예정
=> feat: DemultiplexerBase, KqueueDemultiplexer 객체 구현

src/TimeoutHandler/Makefile, src/TimeoutHandler/TimeoutHandler.cpp, src/TimeoutHandler/TimeoutHandler.hpp
향후 리팩토링 사항
1. 타 객체 설계 후, 변경 사항 반영
- EventHandler
- ClientManager
2. 생성자 호출 시 멤버 변수 초기화 관련 사항 추가 가능
=> feat: TimeoutHandler 객체 구현

src/ClientManager/ClientManager.cpp, src/ClientManager/ClientManager.hpp, src/ClientManager/Makefile
=> feat: ClientManager객체 구현

src/RequestHandler/file_utils.cpp, src/RequestHandler/file_utils.hpp
StaticHandler와 CgiHandler에서 사용될 fileValidation, fileRead 기능이 포함된 네임스페이스.
=> feat: fileUtilites 네임스페이스 구현

src/ClientManager/ClientManager.cpp, src/ClientManager/ClientManager.hpp, src/Demultiplexer/DemultiplexerBase.hpp, src/Demultiplexer/DemultiplexerBase.tpp, src/Demultiplexer/KqueueDemultiplexer.cpp, src/Demultiplexer/KqueueDemultiplexer.hpp, src/ServerManager/ServerManager.hpp, src/ServerManager/ServerManagerRun.cpp, src/include/commonEnums.hpp
=> feat: Event Loop (run()) 객체 구현

src/ResponseBuilder/ErrorPageResolver.cpp, src/ResponseBuilder/ErrorPageResolver.hpp, src/ResponseBuilder/Makefile, src/ResponseBuilder/ResponseBuilder.cpp, src/ResponseBuilder/ResponseBuilder.hpp
ResponseBuilder초안
기본 ResponseBuilder 로직 구현,
ResponseBuilder에서 사용될 커스텀 에러페이지 탐색을 위한 네임스페이스 구현
=> feat: ResponseBuilder 객체 초안

src/EventHandler/EventHandler.hpp, src/EventHandler/EventHandlerSendResponse.cpp
EventHandler의 메소드 sendResponse 구현.
ClientSession의 status 멤버변수를 가지고 있어야 할지 추후 결정.
=> feat: sendResponse

src/ClientManager/ClientManager.cpp, src/ClientManager/ClientManager.hpp, src/ServerManager/ServerManager.hpp, src/ServerManager/ServerManagerRun.cpp, src/TimeoutHandler/TimeoutHandler.cpp
**accessClientSession() : 포인터 반환(null 검사)** 
- ServerManager.run(), TimeoutHandler.checkTimeouts() 내 변경사항 적용
**accessClientSessionMap() : 레퍼런스**
- ServerManager.run() 내 변경사항 적용
- ClientSession 생성자 명세 적용 : (int fd) -> (int listenFd, int clientFd)
**TypeClientSessionMap -> TypeClientMap**
- ServerManager.run() 내 변경사항 적용
- include 수정 및 임시 객체 제거
- 소멸자 내 메모리 해제 로직 추가
- 유효 fd 검증 로직 추가
=> Refactor:client manager

src/EventHandler/EventHandler.cpp, src/EventHandler/EventHandler.hpp, src/EventHandler/EventHandlerReadRequest.cpp, src/EventHandler/EventHandlerRecvRequest.cpp
- readRequest 함수 추가
- readRequest 함수 반환형 변경
- readRequest-> recvRequest 함수명 변경
=> feat: 기존 readRequest 함수 추가 및 이름 변경

src/ClientSession/ClientSession.hpp, src/ConfigParser/ConfigParser.hpp, src/Demultiplexer/DemultiplexerBase.hpp, src/Demultiplexer/KqueueDemultiplexer.hpp, src/EventHandler/EventHandler.hpp, src/GlobalConfig/GlobalConfig.hpp, src/RequestHandler/CgiHandler.hpp, src/RequestHandler/StaticHandler.hpp, src/RequestMessage/RequestMessage.hpp, src/RequestParser/RequestParser.hpp, src/ResponseBuilder/ErrorPageResolver.hpp, src/ResponseBuilder/ResponseBuilder.hpp, src/ServerManager/ServerManager.hpp, src/TimeoutHandler/TimeoutHandler.hpp, src/include/commonEnums.hpp, src/utils/Optional.hpp, src/utils/file_utils.hpp, src/utils/utils.hpp
- C++98 표준에 맞추기 위해 pragma once에서 ifndef XXX_HPP으로 수정
- EventHandler.hpp의 임시 클래스 선언 삭제
- 클래스 선언을 위해 CgiHandler.hpp 생성
=> refactor: 인클루드 가드 변경

src/ClientSession/ClientSession.hpp, src/ConfigParser/ConfigParser.hpp, src/Demultiplexer/DemultiplexerBase.hpp, src/Demultiplexer/KqueueDemultiplexer.hpp, src/EventHandler/EventHandler.hpp, src/GlobalConfig/GlobalConfig.hpp, src/RequestHandler/CgiHandler.cpp, src/RequestHandler/CgiHandler.hpp, src/RequestHandler/Makefile, src/RequestHandler/StaticHandler.hpp, src/RequestMessage/RequestMessage.hpp, src/RequestParser/RequestParser.hpp, src/ResponseBuilder/ErrorPageResolver.hpp, src/ResponseBuilder/ResponseBuilder.hpp, src/ServerManager/ServerManager.hpp, src/TimeoutHandler/TimeoutHandler.hpp, src/include/commonEnums.hpp, src/utils/Optional.hpp, src/utils/file_utils.hpp, src/utils/utils.hpp
수정 필요한 사항
- 시스템콜 에러처리
- cgiPath parse시 유효성 체크
=> feat: cgiHandler 초안

README_CGI.md, config_example.conf, html/cgi-bin/form.php, html/cgi-bin/hello.php, html/cgi-bin/info.php, html/index.html
- PHP CGI 예제 스크립트(hello.php, info.php, form.php) 추가
- 스크립트 예제를 위한 config_example.conf 추가
- PHP CGI 사용 방법에 대한 가이드 문서 추가
이슈 번호: #93
=> feat: PHP CGI 예제 스크립트 및 사용 가이드 추가

src/RequestHandler/StaticHandler.cpp, src/RequestHandler/StaticHandler.hpp
- GET, POST, DELETE의 메소드별 RequestHandle을 각각 구현.
handleGetRequest, handleDeleteRequest, handlePostRequest로 각각 구현
- POST 메소드 간단 파일 업로드 가능하게 구현.
=> feat: static_handler

src/EventHandler/EventHandlerRecvRequest.cpp
RequestParser.parse()함수가 실패하여 EnumSesStatus::REQUEST_ERROR일때,
RequestMessage의 완성정도에 따라 ClientSession의 RequestConfig 포인터가 NULL일 수 있음(== 아직 설정되지 않음).
EventHandler::recvRequest()함수에서 파싱이 완전히 종료되는 시점일때,
ClientSession의 RequestConfig포인터를 필수적으로 설정해줌
(EnumSesStatus::REQUEST_ERROR이거나 EnumSesStatus::READ_COMPLETE일때)
> 테스트 완료후에 PR을 올렸습니다. 
> 이 버그수정 이후엔 403 Forbidden에러가 발생하여 해결이 필요합니다.
=> feat: ClientSessio의 Config pointer NULL 안정성 보장

src/GlobalConfig/GlobalConfig.cpp
- 두번째, 세번째 인자가 주어지지 않았을 때 빠르게 동작하도록 개선
=> refactor: findRequestConfig 개선

html/cgi-bin/hello.php, src/RequestHandler/CgiHandler.cpp, src/ResponseBuilder/ResponseBuilder.cpp, src/ResponseBuilder/ResponseBuilder.hpp, src/utils/file_utils.cpp, src/utils/file_utils.hpp, src/utils/utils.cpp, src/utils/utils.hpp
php 파일 경로 수정, Cgi 스크립트에 전달할 환경변수 추가, Cgi 스크립트로부터 나온 결과에 헤더 추가, u…tils에 size_t_tos 추가, file_utiils에 상대경로 -> 절대경로 함수 추가
=> fix: cgi_handler

src/ClientSession/ClientSession.cpp, src/EventHandler/EventHandler.cpp, src/RequestParser/RequestParser.cpp, src/RequestParser/RequestParser.hpp
=> fix: build error 수정

html/cgi-bin/form.php, html/cgi-bin/info.php, src/RequestHandler/CgiHandler.cpp
isCGI가 쿼리문을 달고 있는 URI를 PATH로 인식 못하는 문제 해결.
예시 PHP파일의 shebang 변경
=> fix: CgiHandler 쿼리문 인식을 위한 isCGI함수 수정, php파일들의 shebang 수정

include_make/Variable.mk, src/Makefile
1. src/Makefile DIRS 자동인식
2. 인클루드 헤더파일 자동인식
=> build: src/Makefile DIRS 자동인식 및 인클루드 자동인식

include_make/Recipe_src.mk, include_make/Variable.mk, src/ClientSession/ClientSession.hpp, src/Makefile
1. 아카이브 파일 참조 순서
2. ubuntu 환경에서의 kqueue 라이브러리 참조 문제
1. SUBS(.a 아카이브 파일) 순서 개선
2. OS 판별 후 linux일 경우 kqueue 라이브러리 참조
=> fix: ubuntu 환경에서의 linkingError

include_make/Variable.mk, src/EventHandler/EventHandler.cpp, src/EventHandler/EventHandlerRecvRequest.cpp, src/EventHandler/EventHandlerSendResponse.cpp, src/include/errorUtils.hpp, src/main.cpp, src/utils/utils.cpp, src/utils/utils.hpp
- int 변수를 직접 stream에 시프트 연산자로 더하는 대신 스트링으로 변환 후 출력
- 컴파일 에러가 발생하지 않도록 DEBUG_LOG 정의 수정
=> fix: 에러 로그 메시지 출력 방식 개선

doc/CONFIG_SYNTAX.md, src/EventHandler/EventHandler.cpp, src/EventHandler/EventHandlerSendResponse.cpp, src/GlobalConfig/GlobalConfig.cpp, src/GlobalConfig/GlobalConfig.hpp, src/main.cpp
- doc/CONFIG_SYNTAX.md 파일 추가하여 설정 파일 문법 문서화
- GlobalConfig와 RequestConfig 출력 형식 개선
- 리다이렉션 및 요청 처리 시 디버그 로그 추가
=> feat: 설정 파일 문서화 및 디버그 로그 개선

test/README.md, test/unit/Makefile, test/unit/TestFramework.hpp, test/unit/test_handle_redirection.cpp, test/unit/test_request_parser.cpp, test/unit/test_runner.cpp, test/unit/test_utils.cpp
- 단위 테스트 프레임워크 구현 (test/unit/TestFramework.hpp)
- utils 모듈, 요청 파서, 리다이렉션 처리 테스트 추가
- 테스트 실행을 위한 Makefile 설정
- test/README.md 파일로 테스트 프레임워크 사용법 문서화
=> test: 테스트 프레임워크 추가 및 유닛 테스트 구현

src/RequestHandler/CgiHandler.cpp, src/RequestHandler/StaticHandler.cpp, src/RequestHandler/StaticHandler.hpp, src/RequestMessage/RequestMessage.hpp
Reverts webserv-blah/webserv#214
=> Revert "feat: HEAD method 구현"

src/ConfigParser/ConfigParser.cpp, src/RequestMessage/RequestMessage.cpp, src/RequestMessage/RequestMessage.hpp, src/RequestParser/RequestParserBody.cpp, src/RequestParser/RequestParserStartLine.cpp
Reverts webserv-blah/webserv#213
=> Revert "feat: RequestMessage & Parser에 HEAD 메서드 추가"

.gitignore, src/EventHandler/EventHandler.cpp, src/ResponseBuilder/ErrorPageResolver.cpp, src/ResponseBuilder/ErrorPageResolver.hpp, src/ResponseBuilder/ResponseBuilder.cpp, src/utils/file_utils.cpp, src/utils/file_utils.hpp, test/unit/test_error_page_resolver.cpp
- ErrorPageResolver::resolveErrorPage 매개변수 수정
- 사용자 정의 에러 페이지 찾는 로직 수정
- FileUtilities:joinPaths() 추가
- errorPageResolver 유닛테스트 추가
- replaceTemplatePlaceholders 수정
#168
=> fix: errorPageResolver 수정

config/config.conf, src/ConfigParser/ConfigParser.cpp, src/ConfigParser/ConfigParser.hpp
- ConfigParser::isDuplicateServer 추가
=> fix: 설정파일 파서에서 중복된 포트 설정 허용하지 않게 수정

src/ResponseBuilder/ResponseBuilder.cpp
- URI_TOO_LARGE의 phrase 문자열 추가
- CONTENT_TOO_LARGE의 phrase 문자열 수정
- 서버 기본 설정 (`#define URI_MAX_LENGTH 2048`)
- 2049자 uri
```shell
printf "GET /vquqnyjmkTjPuKaVHkwLepwLheBjogwiifuYaryLlefMWxLDHLdfuuHCsOanrukXvedGzyMHOVtpSGJgCmxxRyjdIzRUBiriOFGhuyfEGIZmqGljTKetFZkLoessCZeWEBUQFqKbMaQkfcpxcpUYHVOWukVGtwNUlEfiSovYHRsUFWHtwGKqCWxkHCKUwmOMJSsrIzWrumalheSGQqmAXzILazVzUBxfAdqMvdCBgKxqGTOZaTTvgRjElxiKGwIHwYOwUSDykdUQNoAFTKRzicmOFZIDGAszRbjiEzNlOzpWxvBmzIIYwMgGGIPOWbssuYGgSTbZjanjPrXQiEdaMDntwHftwPVMGAnzNQvYMTZUKjjHkzQjwprHaUnvIxzDphyvorDqIOvjDYXVXfGJrrPJYBQlRUmeDmwdumIzBwREkCSDLIKYaQDNaqsGHejKHuolWJhYGKrJtQJlbAhCoieqkfBGlndDXJyuBkPSCgmEBZTObEgEhzqTcdEalayWXShaeSsmDMPqZGhxAQkwXjKuerMvjXxWrnySzPcLLJbTrlgVMzUREGQbgqNInsPUHXqribTPHACCeRMwHqBnyDAYXCRwwLfGnoOCyUruZbIZLFLqnRVCoTAJAWYodskzzZSYdtodZpbZoRwdp …
```
=> fix: ResponseBuilder::getReasonPhrase 추가 및 수정

src/ResponseBuilder/ErrorPageResolver.cpp, src/ResponseBuilder/ResponseBuilder.cpp
#258 에서 놓친 `ErrorPageResolver` 메서드들에도 추가, 수정사항을 반영하였습니다.
=> fix: ErrorPageResolver에도 URI too large 추가

src/ServerManager/ServerManager.hpp
- isServerRunning 프라이빗 함수로 변경
- notifyClientsShutdown 삭제
- 불필요하게 장황한 주석 정리
- 관련성 있는 함수들을 묶어서 정리
=> refactor: ServerManager 정리

src/EventHandler/EventHandler.cpp, src/EventHandler/EventHandler.hpp, src/RequestHandler/StaticHandler.cpp, src/RequestHandler/StaticHandler.hpp
- StaticHandler으로부터 EventHandler로
isMethodAllowed 이동
=> fix: CGI요청일 때 isMethodAllowed 검사
