src/Makefile
src/RequestMessage/RequestMessage.cpp
src/RequestMessage/RequestMessage.hpp
src/RequestParser/Makefile
src/RequestParser/RequestParser.cpp
src/RequestParser/RequestParser.hpp
src/utils/utils.cpp
src/utils/utils.hpp

- `src/utils`에 string to size_t기능의 함수 추가
- RequestMessage 객체 수정
- enum requestStatus 추가
- 메타 데이터 추가(: header-field 중 주요한 데이터)
- message 출력함수 추가

feat: RequestParser 객체 구현

---

src/ConfigParser/ConfigParser.cpp
src/ConfigParser/ConfigParser.hpp
src/ConfigParser/parse_simple_directives.cpp
src/GlobalConfig/GlobalConfig.cpp
src/GlobalConfig/GlobalConfig.hpp

- GlobalConfig의 퍼블릭 메서드
- 리스닝 소켓 디스크립터, 도메인 이름, 대상 URL에 해당하는 요청 설정을 찾음.
findServerConfig() 구현
- findRequestConfig로부터 호출되어 도메인 이름에 해당하는 서버 설정을 찾음
findLocationConfig() 구현
- findRequestConfig로부터 호출되어 대상 URI에 해당하는 location 설정을 찾음
- ConfigParser::parse()에서 서버 블록을 찾지 못하면 예외를 던지도록 수정
- 클래스명 ReqHandleConfig -> RequestConfig로 수정
- 멤버변수명 ReqHandleConfig::reqHandling -> reqConfig로 수정
#25

feat: findRequestConfig() 구현

---

Makefile
_request_msg_test.sh
src/ClientSession/ClientSession.cpp
src/ClientSession/ClientSession.hpp
src/ClientSession/Makefile
src/Makefile
src/RequestMessage/RequestMessage.cpp
src/main.cpp
src/readRequest.cpp

1. ClientSession 구현
2. EventHandler.handleClientRead() 내부의 readRequest() 기본 로직 임시로 구현
3. 테스트 기능
- `main.cpp`에서 `readRequest()` 호출
- `readRequest.cpp`에서 `recv()`가 아닌 방법으로 임시 구현
- `_request_msg_test.sh`로 request message 입력

feat: ClientSession 구현 및 RequestParser 테스트 가능

---

src/EventHandler/EventHandler.cpp
src/EventHandler/EventHandler.hpp
src/EventHandler/EventHandlerReadRequest.cpp
src/EventHandler/EventHandlerSendResponse.cpp
src/EventHandler/Makefile
src/ServerManager/ServerManagerRun.cpp
src/TimeoutHandler/TimeoutHandler.cpp

@taerakim 
제안이라기보단 통보..?이지만 readRequest에서 parser를 넘겨드릴 필요가 없었습니다..!
둘다 EventHandler의 멤버이다보니 내부적으로 사용하시면 됩니다. 
기존에 작업하신 내용 옮기실 때 수정하시면 될 것 같습니다!
@nowead @taerakim 
일단 기존 명세대로 포인터를 반환받으면, 역참조한 내용을 넘겨주도록 했습니다.
다만 각 값들이 null일리 없다....라고 생각하면서 null가드를 따로 하지 않았습니다. 
한편으로는 null일리 없다면 굳이 포인터일 필요가 있을지 모르겠습니다..! 레퍼런스로 변경하는게 어떨까요?

Feat: Event Handler 객체 구현

---

src/ClientSession/ClientSession.cpp
src/ClientSession/ClientSession.hpp
src/RequestMessage/RequestMessage.cpp
src/RequestMessage/RequestMessage.hpp
src/RequestParser/RequestParser.cpp
src/RequestParser/RequestParser.hpp
src/utils/utils.cpp
src/utils/utils.hpp

- READ_CONTINUE시 처리 로직 (<- readBuffer)
- Body와 Content-Length
- 청크 전송 처리
- Request완료시 메타데이터 default값 설정
- field-line파싱 고도화
- ssize_t -> size_t 변경

feat: RequestParser 정상화, 고도화 및 예외 처리 강화

---

src/ClientSession/ClientSession.cpp
src/ClientSession/ClientSession.hpp
src/RequestParser/RequestParser.cpp
src/RequestParser/RequestParser.hpp

- ClientSession:: 로직내에 config를 설정하는 로직 추가
- RequestParser를 호출 시, Config가 존재하면 clientMaxBodySize를 넘겨주고, 존재하지 않는 경우에는 BODY_MAX_LENGTH(기본 1MB)를 설정하는 로직 추가
- header field들을 다 읽고난후, 처리 과정 추가
- 요청 헤더 필드(Host) 존재 검증
- Content-Length가 0이거나 Transfer-Encoding이 없으면 RequestMessage 완료 처리(REQ_DONE)
- RequestParser에 setConfigBodyLength() 메서드를 추가하여 Config에서 넘어오는 clientMaxBodySize 값을 반영
- Body가 설정된 최대 길이를 초과할 경우, 413(Request Entity Too Large) 에러 코드를 반환하도록 구현
- ClientSession 및 RequestParser의 메서드에 대한 주석을 보강
- 요청 메시지 테스트 후 발견된 문제를 수정
- readData와 readBuffer의 합칠때 순서 오류
- ClientSession의 RequestConfig*를 const RequestConfig*로 변경하여 Config 참조 안정성을 개선
- Body 파싱 시, 남은 데이터(readBuffer) 처리 로직을 보강했습니다.

feat: RequestParser 파싱과정에 GlobalConfig 사용 로직 추가

---

src/ConfigParser/parse_server_block.cpp
src/ServerManager/ServerManager.cpp
src/ServerManager/ServerManager.hpp

- ServerManager::setupListeningSockets를 작은 함수들로 리팩토링
- IPv6 주소 지원을 제거하고, IPv4 주소만 지원
이슈 번호: #65

feat: IPv6 주소 지원 제거

---

src/utils/file_utils.cpp

1. 기존의 using namespace FileUtilities; 를 사용해서 함수를 정의하는 잘못된 방식 수정했습니다.
함수 정의 부분을 namespace로 감싸주었습니다.
2. std::string.back() 함수가 사용 불가능 합니다. 인덱스 접근 방식으로 대체하였습니다.

fix: file_utils namespace scope 수정 및 string.back() 제거

---

src/ClientManager/ClientManager.cpp
src/ClientManager/ClientManager.hpp
src/ClientSession/ClientSession.cpp
src/ClientSession/ClientSession.hpp
src/EventHandler/EventHandler.cpp
src/EventHandler/EventHandler.hpp

**1. ClientSession내 clientIP 정보 지원**
: requestHandling 시 필요한 정보로 ClientSession 초기화시 세팅됩니다.
ClientSession 생성 시 필요한 정보가 늘어남에 따라 생성 시점(clientManager.addClient())을 
EventHandler의 handleServerReadEvent() 내부로 이동했습니다. 
아직 ServerManager.run() 내 기존 생성 위치는 수정되지 않았으며, 이어서 작업할 이벤트 루프 리팩토링에서 해당 사항 반영할 예정입니다.
이 외에도 IPv4주소를 문자열로 변환하는 로직도 추가되었습니다. 
**2. 기타**
- 의존성 개선을 위한 include 위치 수정 (이에 따라 recvRequest, sendResponse 구현파일 내 <sys/socket.h> 를 인클루드 해야합니다.)
- Client 이벤트 핸들리 메소드들의 반환값 수정: int -> EnumSesStatus
- 주석 추가
: recvRequest(), sendResponse() 파트 완성 및 멤버 변수 생성자 등 최종 명세가 변경될 경우 반영할 예정

Refactor: eventhandler

---

src/EventHandler/EventHandler.cpp
src/RequestHandler/CgiHandler.cpp
src/RequestHandler/CgiHandler.hpp

- 설정파일에서 정의된 내용대로 cgi 스크립트를 구별하도록 수정했습니다.
- 요청 url이 설정파일에서 정의된 문자열로 끝날때 cgi 스크립트로 간주합니다.

feat: CgiHandler::isCGI() 로직 수정

---

src/ConfigParser/ConfigParser.hpp
src/ConfigParser/parse_server_block.cpp
src/ConfigParser/parse_simple_directives.cpp
src/GlobalConfig/GlobalConfig.cpp
src/GlobalConfig/GlobalConfig.hpp
src/ServerManager/ServerManager.cpp
src/ServerManager/ServerManager.hpp
src/main.cpp
src/utils/file_utils.cpp
src/utils/utils.cpp
src/utils/utils.hpp

- atexit을 삭제하고 main문에 try-catch문을 도입했습니다.
- cpp98에 맞지 않는 함수들을 수정했습니다.
- 네임스페이스가 올바르지 않은 코드를 수정했습니다.
- ServerManager의 메서드들에 const 수식어를 추가했습니다.
- ServerManager.hpp에서 isServerRunning() 함수에 const 한정자 추가
- std::make_pair 대신 직접 pair 생성자 사용
- isListeningSocket 함수 구현 추가
- 변수 초기화 위치 수정 및 공백 정리
이슈 번호: #126, #133

fix: atexit 대체 및 cpp98 표준에 맞추어 함수 수정

---

html/error/default_error.html
src/ResponseBuilder/ErrorPageResolver.cpp
src/ResponseBuilder/ErrorPageResolver.hpp

- HTML/error 디렉토리 생성 및 default_error.html 템플릿 파일 추가
- 템플릿에 {{ERROR_CODE}}, {{ERROR_TEXT}}, {{ERROR_DESCRIPTION}} 플레이스홀더 적용
- ErrorPageResolver 클래스 확장:
- 템플릿 파일 로드 및 플레이스홀더 치환 기능 추가
- 상태 코드별 설명 텍스트 생성 함수 추가
- 폴백 메커니즘으로 최소 텍스트 에러 페이지 구현
관련 이슈: #103

feat: 기본 에러 페이지 템플릿 구현

---

src/ClientManager/ClientManager.cpp
src/Demultiplexer/KqueueDemultiplexer.cpp
src/EventHandler/EventHandler.cpp
src/EventHandler/EventHandlerRecvRequest.cpp
src/ServerManager/ServerManager.cpp
src/ServerManager/ServerManagerRun.cpp
src/utils/examples/README.md
src/utils/examples/error_handling_example.cpp
src/utils/file_utils.cpp

- errorUtils.hpp를 상대경로로 include하도록 수정
이슈 번호: #68

fix: error status를 전역 스코프에서 호출하도록 수정

---

src/ClientSession/ClientSession.cpp
src/ClientSession/ClientSession.hpp
src/Demultiplexer/DemultiplexerBase.hpp
src/Demultiplexer/DemultiplexerBase.tpp
src/Demultiplexer/KqueueDemultiplexer.cpp
src/Demultiplexer/KqueueDemultiplexer.hpp
src/EventHandler/EventHandler.cpp
src/ServerManager/ServerManager.cpp
src/ServerManager/ServerManagerRun.cpp
src/TimeoutHandler/TimeoutHandler.cpp
src/TimeoutHandler/TimeoutHandler.hpp

항시 무한정 대기: timeout값에 nullptr 넘김
if 연결된 클라이언트 존재 : 가장 임박한 만료시간까지 대기 
else : 기존처럼 대기
**(1) TimeoutHandler 내 임박한 만료시간 관리 및 getter 생성
(2) 제공된 만료시간 정보를 타임아웃 주기에 반영**

Fix: Timeout 체크 주기 개선

---

src/ClientSession/ClientSession.cpp
src/ClientSession/ClientSession.hpp
src/EventHandler/EventHandler.cpp
src/EventHandler/EventHandlerRecvRequest.cpp
src/RequestHandler/CgiHandler.cpp
src/RequestParser/RequestParser.cpp

- ClientSession::getConfigPtr()를 getConfig()로 통합
- ClientSession::getReqMsgPtr()를 getReqMsg()로 통합
config_와 reqMsg_는 값이 있을지 없을지 모르는 멤버 변수이기 때문에,
레퍼런스로 접근하는 것은 바람직하지 않음.
- ClientSession::defConfig_ 추가
config_의 값이 계속해서 변하기 때문에, 변하지 않는 기본값을 저장할 멤버 변수
생성자에서 설정되기 때문에 항상 변하지 않는 값을 보장함
- config_의 값이 없을 시 getConfig()에서 defConfig_를 반환하도록 수정

refactor: reqConfig, reqMsg 접근방법 수정

---

include_make/Link.mk
include_make/Recipe_src.mk
include_make/Recipe_subsrc.mk
include_make/Verbose.mk

1. 로그 단순화 기능 추가
2. 로그 단순화를 default로 설정
3. 기존의 컬러타이틀 방식은 `NOTALL`변수 설정으로 가능
---
1. 새로운 로그 `$make`
2. 기존의 로그 `$make NOTALL=1`

build: Makefile  로그 단순화한 기능 추가 및 기본으로 설정

---

src/ClientSession/ClientSession.cpp
src/ClientSession/ClientSession.hpp
src/ServerManager/ServerManagerRun.cpp
src/TimeoutHandler/TimeoutHandler.cpp
src/TimeoutHandler/TimeoutHandler.hpp

: Idle과 요청 진행 시의 상황을 구분하지 않아, 정상적으로 웹페이지를 보던 클라이언트도 408에러를 수신하게 됨.
즉, Idle의 타임아웃 상황에 요청 타임아웃 결과를 반환
**1. ClientSession 내 isReceiving() 판별메소드 추가**
- 목적: 클라이언트가 요청을 수신 중에 있는지, 요청 수신을 완료되었는지 판별
- 구현 방법: reqMsg_ 멤버변수가  null일 경우 수신완료, 아닐경우 수신 중
- 근거: 요청 수신 완료시 필연적으로 setWriteBuffer()를 호출하여 readMsg를 초기화하게 되어있음. 따라서 수신 완료시 null임이 보장 됨. 
**2. Idle 상태와 Request 처리에서의 Timeout 구분**
| 항목                | Idle 상태      | 요청 수신 중                                   |
|---------------------|----------------|------------------------------------------------|
| 만료 시각 갱신 기준 | `IDLE_TIMEOUT` |                  `REQ_TIMEOUT`                 |
| 만료 시 처리        | 리소스만 정리  | 클라이언트에 408 에러 반환 시도 후 리소스 정리 | |
- TimeoutHandler.updateTimeout() : 상태구분을 위한 파라미터 추가, 파라미터에 따른 만료시각 갱신 값 구분
- TimeoutHandler.checkTimeout() : …

fix: Idle Timeout과 Request Timeout 구분

---

src/EventHandler/EventHandler.cpp
src/EventHandler/EventHandler.hpp
src/RequestHandler/StaticHandler.cpp
src/RequestHandler/StaticHandler.hpp

- 요청 메세지를 파싱하고 cgi 요청인지 정적 요청인지 판단하기 전에 리다이렉션 여부 확인
- StaticHandler의 메서드에서 EventHandler의 메서드로 이동
- rspBuilder를 responseBuilder로 이름 통일
향후 테스트가 필요합니다.

refactor: handleRedirection

---

src/main.cpp

signal 종료 시 globalServerRunning 값이 false로 바뀝니다. 
이를 이용해 signal 종료 여부를 판단후, 해당하지 않을 경우에만 에러로그 출력하도록 수정했습니다!(main.cpp)

fix: signal 종료 시 error 출력 비활성화(#186)

---

.gitignore
.gitmessage.txt

- 커밋 메시지 작성 시 한국어로 작성하도록 안내 추가
- 커밋 메시지 예시 추가
- CLAUDE.md 파일을 .gitignore에 추가하여 브랜치 간 유지되도록 설정

docs: 커밋 메시지 가이드라인 업데이트 및 CLAUDE.md 관리 설정

---

include_make/Variable.mk
src/Demultiplexer/KqueueDemultiplexer.cpp
src/Demultiplexer/KqueueDemultiplexer.hpp

kqueue 라이브러리 인식하도록 variable.mk 수정
c++98에서 지원하지 않는 nullptr -> NULL로 수정
mac환경에서 사용되도록 제한해두 #ifdef __APPLE #endif 주석처리

fix: ubuntu 환경에서 kqueue라이브러리 인식하도록 수정 및 기타(#194)

---

.gitignore
42tester.mk
Dockerfile
config/42tester.conf

- `42tester.conf`
1. 과제 페이지에서 ubuntu_tester를 다운받아 `./`경로에 준비한다.
2. $`make t`로 컨테이너를 준비하고 실행한다.
3. 터미널 두 개를 켜 `$make tgo`로 컨테이너에 접속한 다음, 각각 $TESTER, $SERVER 를 실행한다.

feat: 42테스터를 위한 컨테이너 환경 준비

---

src/RequestHandler/CgiHandler.cpp

`return uriWithoutQuery.compare(uriWithoutQuery.size() - cgiExtension.size(), cgiExtension.size(), cgiExtension) == 0;`
`return uriWithoutQuery.find(cgiExtension, uriWithoutQuery.size() - cgiExtension.size()) == std::string::npos;`

fix: isCGI함수에서 확장자 검사 방식 변경 compare -> find

---

src/EventHandler/EventHandlerRecvRequest.cpp
src/RequestHandler/CgiHandler.cpp
src/RequestParser/RequestParser.cpp

1. 같은 포트를 공유하는 다른 서버를 테스트하던 중, targetURI에 Domain name을 포함하면 정상작동하지 않음
2. #189 때 추가되었던 targetURI의 domain편집과 findRequestConfig의 순서를 바꿔주면 해결된다는 사실을 알았음
- 입력했던 RequestMessage
`printf "GET A:8080/ HTTP/1.1\r\nHost: d\r\n\r\n" | nc 127.0.0.1 8080`
- 사용했던 multi_port.conf
```
server {
listen 8080;
server_name localhost;
root ./www/html;
index index.html;
}
server {
listen 8080;
server_name A;
root ./www/html;
index index2.html;
}
server {
listen 8080;
server_name B;
root ./www/html;
index index3.html;
}
```

fix: RequestParser에서 findRequestConfig 로직 순서 변경 및 도메인네임 파싱 추가

---

html/cgi-bin/form.py
html/cgi-bin/hello.py
html/cgi-bin/info.py
src/ClientSession/ClientSession.cpp
src/ClientSession/ClientSession.hpp
src/EventHandler/EventHandler.cpp
src/ServerManager/ServerManagerRun.cpp
src/TimeoutHandler/TimeoutHandler.cpp

> [ 📝 평가 요구사항 中... ]
> There should be only one read or one write per client per select.
하나의 이벤트 당 `하나의`&`한 번의` I/O만 처리 하도록 변경합니다.
: 기존 handleReadEvent, handleError 내 sendResponse 로직을 제거했습니다.
따라서 두 메소드에서는 response내용을 clientSession 내 write 버퍼에 세팅하는 역할까지만 수행합니다.
또한 handleReadEvent에서는 recv에 따른 status 반환만 가능합니다.
(`READ_CONTINUE`, `READ_COMPLETE`, `REQUEST_ERROR`, `CONNECTION_CLOSED`)
: 기존`CONNECTION_CLOSED`로 즉각 연결을 종료하던 방식이 일부 상황에 대해 불가능해졌습니다.
따라서 향후 연결 정리가 필요한지 여부를 파악할 수 있는 멤버변수를 추가했습니다. 
기본적으로 false로 초기화되며, setConnectionClosed()를 통해 true로 변환할 수 있습니다. 
`REQUEST_ERROR` 혹은 타임아웃 시, 해당 메소드를 호출합니다(바로 write가 불가한 경우).
handleWriteEvent내에서 response 전송 후, isConnectionClosed()를 통해 해당 플래그를 확인합니다. 
true일 경우 `CONNECTION_CLOSED` 반환 후 연결을 정리합니다. 
: 기존에는 timeout 시, 그리고 graceful shutdown 시 handleError를 …

refactor: 하나의 event당 하나의, 한 번의 I/O만 처리하도록 수정

---

src/ConfigParser/parse_location_block.cpp

- 메서드 지시자가 없으면 기본값(GET, POST, DELETE 허용)을 설정합니다.
- 메서드 지시자 뒤에 값 없이 세미콜론으로 끝나면 아무 지시자도 허용하지 않습니다.
- 메서드 지시자가 여러개 오면 허용되는 메서드를 합집합으로 계산합니다.

feat: 아무 메서드도 허용하지 않는 설정 방법 추가

---

src/ConfigParser/ConfigParser.cpp
src/ConfigParser/ConfigParser.hpp
src/ConfigParser/parse_location_block.cpp
src/GlobalConfig/GlobalConfig.cpp
src/GlobalConfig/GlobalConfig.hpp
src/RequestHandler/CgiHandler.cpp
src/RequestHandler/StaticHandler.cpp

- LocationConfig::path를 RequestConfig::locationPath로 이동
- index의 파일의 경로를 구할때
root + locationPath + indexFile으로 구하도록 수정
- 함수 이름들에서 Handling을 Config로 수정
- targetUrl -> targetUri로 수정
테스트 방법
- 루트 디렉토리가 아닌 장소에 있는 cgi 파일을 인덱스 파일로 지정하고
해당 파일의 디렉토리에 GET 요청을 보냈을 때 cgi로 처리되는것을 확인

fix: 인덱스 파일의 경로을 올바르게 구하도록 수정

---

src/ConfigParser/parse_location_block.cpp
src/EventHandler/EventHandler.cpp
src/GlobalConfig/GlobalConfig.cpp
src/RequestHandler/CgiHandler.cpp
src/RequestHandler/CgiHandler.hpp
src/RequestHandler/StaticHandler.cpp
src/RequestMessage/RequestMessage.cpp
src/utils/file_utils.cpp

- 디렉토리의 실행 권한이 없어서 파일을 삭제할 수 없을때
서버가 forbidden을 반환하도록 수정
fix: isCGI가 DELETE 요청에 false로 반환하도록 수정
- isCGI 매개변수 추가: const EnumMethod
- DELETE 실행 흐름 디버깅 메세지 출력 코드 추가
fix: location path 앞에 '/'가 오도록 수정
- 가장 앞글자가 "/"가 아니면 예외 발생
- RequestConfig::print에서 location path를 출력하도록 변경
- RequestMessage::printMetaData의 조건식 오류 수정

fix: 파일의 중간경로의 실행권한이 없을때 forbidden 반환

---

src/ConfigParser/ConfigParser.hpp

컨테이너에서 c++98을 만족하는지 테스트해보았습니다.

chore: std::find 헤더파일 인클루드 누락
